#!/bin/bash
# Gmail API Environment Variables
# Generated by auth_setup utility

export GMAIL_CLIENT_SECRET_JSON="./secrets/client-secret.json"
export GMAIL_TOKEN_JSON="./secrets/token.json"

echo "✅ Gmail API environment variables set:"
echo "   GMAIL_CLIENT_SECRET_JSON=$GMAIL_CLIENT_SECRET_JSON"
echo "   GMAIL_TOKEN_JSON=$GMAIL_TOKEN_JSON"
echo ""
echo "You can now run: cargo run"
